version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: washify-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-washify}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-washify_dev_password}
      POSTGRES_DB: ${POSTGRES_DB:-washify_dev}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./packages/db/init:/docker-entrypoint-initdb.d
    networks:
      - washify-network

  redis:
    image: redis:7-alpine
    container_name: washify-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - washify-network

  adminer:
    image: adminer:latest
    container_name: washify-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - washify-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  washify-network:
    driver: bridge 